import {
  DATA_SIZE,
  FLASH_WORDS,
  IO_BASE,
  RAMEND,
  SE,
  SMCR,
  SPH_ADDR,
  SPL_ADDR,
  SREG_ADDR,
} from "./constants";
import { Sreg } from "./sreg";
import { UnknownOpcodeError } from "./errors";
import type {
  CycleListener,
  Executor,
  InstructionHandler,
  InterruptAcknowledgeResolver,
  IoReadHook,
  IoWriteHook,
  PendingInterrupt,
  ProgramMemoryReadHook,
  ProfileRunListener,
  ProfileRunState,
  SpmInstructionHook,
  TraceListener,
  TraceState,
} from "./types";
import type { CpuSnapshot } from "../snapshot";
import { SREG_I } from "./alu";
// The execution cores (~3,500 generated lines) live in their own module to keep
// cpu.ts focused on hand-written logic. Generated by scripts/generate-fast-core.ts.
import { runFastProfiled, runGeneratedFastCore } from "./generated/cores";
// The guarded fast blocks (classifier/guard/runner triples) live in their own
// module too; cpu.ts keeps only the per-PC kind cache and the dispatch below.
import {
  FAST_BLOCK_NONE,
  FAST_BLOCK_UNKNOWN,
  classifyFastBlock,
  fastBlockProfileKind,
  runFastBlock,
} from "./fast-blocks";

const NOOP = (): void => {};

function normalizeClockEventDelay(cyclesFromNow: number): number {
  if (!Number.isFinite(cyclesFromNow)) return 1;
  return Math.max(1, Math.trunc(cyclesFromNow));
}

export type Udivmodsi4RegionMode = "handwritten" | "generated-cfg" | "semantic-direct";

/**
 * A scheduled clock event (Phase 7 event-driven peripherals). Peripherals call
 * `addClockEvent` to fire `callback` at an absolute `cycles` boundary instead of
 * being ticked every instruction. Nodes form a sorted singly-linked list and are
 * pooled to avoid per-schedule allocation.
 */
interface ClockEvent {
  cycles: number;
  callback: () => void;
  next: ClockEvent | undefined;
}

/**
 * The ATmega328P core: program memory (flash), the flat data space (registers +
 * I/O + SRAM), and the CPU's own state (PC, cycles, SP, SREG).
 *
 * Phase 1 is the shell — no instruction execution yet. `writeData` is the single
 * choke point peripherals will hook in later phases.
 */
export class CPU {
  /**
   * Selector for the `__udivmodsi4` hot region. The semantic-direct path is the
   * default after beating the generated CFG block on sensor-format.
   */
  static udivmodsi4RegionMode: Udivmodsi4RegionMode = "semantic-direct";

  /**
   * Per-instance selector for the `__udivmodsi4` hot region. Defaults from the
   * static value so benchmark scripts can still choose a process-wide default
   * before constructing CPUs without mutating existing instances.
   */
  udivmodsi4RegionMode: Udivmodsi4RegionMode = CPU.udivmodsi4RegionMode;

  /** Program memory: 16-bit words, indexed by the program counter. */
  readonly flash: Uint16Array;
  /** Data space: R0..R31, I/O registers, then SRAM — one flat byte array. */
  readonly data: Uint8Array;
  /** Status register accessor (mirrors data[0x5F]). */
  readonly sreg: Sreg;

  /** Program counter (word index into `flash`). */
  pc = 0;
  /** Boot-vector offset applied when MCUCR.IVSEL relocates interrupt vectors. */
  interruptVectorBase = 0;
  /**
   * Internal cycle counter (the unit of simulated time).
   * @internal Exposed for the generated execution cores (see generated/cores.ts);
   * not part of the supported public API — use the `cycles` accessor.
   */
  _cycles = 0;

  /**
   * Total elapsed clock cycles — the unit of simulated time. Writes to this
   * property fire cycle listeners immediately via the setter so that timers
   * and other peripherals can observe per-cycle boundaries when running in
   * `"cycle-exact"` timing mode. In `"fast"` mode (default) the setter still
   * fires the listeners, but coalesces the whole instruction's worth of
   * cycles into one call — preserving the existing performance profile.
   */
  get cycles(): number {
    return this._cycles;
  }
  set cycles(value: number) {
    const delta = value - this._cycles;
    if (!this.cycleExact) {
      this._cycles = value;
      if (delta <= 0) return;
      // Inlined hot guards: skip the notifyCycles() call frame entirely when no
      // cycle listeners are wired (the production case — timers/USART/ADC use
      // addClockEvent, exti attaches with cycleListener:false), and compare against
      // the cached scalar next-event boundary instead of dereferencing the queue
      // head. `nextEventAt` is +Infinity when nothing is scheduled, so this is a
      // single numeric compare on the common path.
      if (this.cycleListeners.length !== 0) this.notifyCycles(delta);
      if (this._cycles >= this.nextEventAt) this.runDueClockEvents();
      return;
    }

    if (delta <= 0) {
      this._cycles = value;
      return;
    }
    this.advanceCycleExact(delta);
  }

  private advanceCycleExact(delta: number): void {
    for (let i = 0; i < delta; i += 1) {
      this._cycles += 1;
      if (this._cycles >= this.nextEventAt) this.runDueClockEvents();
      this.notifyCycles(1);
    }
  }

  /** @internal generated-core surface (see generated/cores.ts). */
  readonly traceListeners: TraceListener[] = [];
  private readonly cycleListeners: CycleListener[] = [];
  private readonly pendingCycleListenerRemovals: CycleListener[] = [];
  private readonly pendingCycleListenerRemovalDepths = new Map<CycleListener, number>();
  private cycleListenerDispatchDepth = 0;
  private readonly pendingInterrupts: PendingInterrupt[] = [];
  private interruptDeferred = false;
  private programMemoryReadHook: ProgramMemoryReadHook | undefined;
  private spmInstructionHook: SpmInstructionHook | undefined;
  // Sparse, indexed by data-space address; peripherals install hooks here.
  /** @internal fast-block surface (see fast-blocks.ts). */
  readonly writeHooks: Array<IoWriteHook[] | undefined> = [];
  /** @internal fast-block surface (see fast-blocks.ts). */
  readonly readHooks: Array<IoReadHook[] | undefined> = [];
  private readonly wdrListeners: Array<() => void> = [];
  private readonly sleepListeners: Array<(mode: number) => void> = [];
  private readonly wakeStartListeners: Array<(wakeCycle: number) => void> = [];
  private readonly wakeListeners: Array<(wakeCycle: number) => void> = [];
  private readonly flagListeners: Array<Array<(raised: number) => void> | undefined> = [];
  // Event-scheduled peripheral clock events (sorted by absolute cycle), plus a
  // small reuse pool. `nextClockEvent === undefined` is the common case (no
  // peripheral has scheduled anything), so the hot path is a single null check.
  private nextClockEvent: ClockEvent | undefined = undefined;
  // Scalar mirror of `nextClockEvent?.cycles ?? +Infinity`, read on the
  // per-instruction hot path (cycles setter) so it never dereferences the queue
  // head there. Kept in sync at the few cold head-mutation sites.
  private nextEventAt = Number.POSITIVE_INFINITY;
  private readonly clockEventPool: ClockEvent[] = [];
  /** @internal generated-core surface (see generated/cores.ts). */
  sleeping = false;
  /** @internal generated-core surface (see generated/cores.ts). */
  executor?: Executor;
  /**
   * Phase 4 predecode: lazily filled handler-per-PC cache. `tick()` resolves the
   * handler from `flash[pc]` once and reuses it on later executions of the same
   * PC, dispatching without an `executor.execute()` call frame. Invalidated when
   * flash content changes (`reset`, `restore`, or an explicit
   * `invalidateDecodeCache()` after a direct `flash` write).
   */
  /** @internal generated-core surface (see generated/cores.ts). */
  decodeCache: Array<InstructionHandler | undefined> = [];
  /**
   * PC-local classifier for guarded fast blocks. Unlike `decodeCache`, this
   * stores only tiny numeric kinds for block shapes that were already proven by
   * parity tests; `FAST_BLOCK_NONE` avoids re-checking non-matching candidate PCs.
   */
  private fastBlockCache: number[] = [];

  // --- Debug state (Phase 11) ---
  /** PC addresses that should pause execution before the instruction runs. */
  readonly breakpoints = new Set<number>();
  /** When true, an unknown opcode stops execution and is captured as `error`. */
  pauseOnUnknownOpcode = false;
  private _breakpointHit = false;
  private _error: unknown = null;

  // --- Timing mode (Phase 12) ---
  /**
   * How peripherals observe simulated time:
   *   - `"fast"`: one notifyCycles(N) per instruction (cheap).
   *   - `"cycle-exact"`: N notifyCycles(1) calls so peripheral events line up
   *     with individual CPU cycles inside multi-cycle instructions.
   */
  private _timing: "fast" | "cycle-exact" = "fast";
  /** Mirror of `_timing === "cycle-exact"`, read on the per-instruction hot path. */
  private cycleExact = false;
  get timing(): "fast" | "cycle-exact" {
    return this._timing;
  }
  set timing(value: "fast" | "cycle-exact") {
    this._timing = value;
    this.cycleExact = value === "cycle-exact";
  }

  constructor(flash?: Uint16Array) {
    this.flash = flash ?? new Uint16Array(FLASH_WORDS);
    this.data = new Uint8Array(DATA_SIZE);
    this.sreg = new Sreg(this.data);
    this.reset();
  }

  /** Power-on state: clear data space, PC=0, cycles=0, SP=RAMEND. */
  reset(): void {
    this.pc = 0;
    this.interruptVectorBase = 0;
    this.cycles = 0;
    this.sleeping = false;
    this.pendingInterrupts.length = 0;
    this.interruptDeferred = false;
    this.data.fill(0);
    this.SP = RAMEND;
    // Flash may have been (re)loaded just before reset(); drop stale handlers.
    this.invalidateDecodeCache();
    // Power-on clears any scheduled peripheral events; peripherals re-arm in
    // their own reset()/write hooks from the freshly zeroed register state.
    this.nextClockEvent = undefined;
    this.nextEventAt = Number.POSITIVE_INFINITY;
  }

  /** Enter sleep (SLEEP instruction). Only sleeps if SMCR.SE is set, per hardware. */
  sleep(): void {
    if ((this.data[SMCR]! & (1 << SE)) === 0) return;
    this.sleeping = true;
    const mode = this.sleepMode;
    for (const listener of [...this.sleepListeners]) listener(mode);
  }

  get isSleeping(): boolean {
    return this.sleeping;
  }

  get sleepMode(): number {
    return (this.data[SMCR]! >> 1) & 0x07;
  }

  /** Register a listener fired by the WDR instruction (watchdog reset). */
  onWdr(listener: () => void): () => void {
    this.wdrListeners.push(listener);
    return () => {
      const index = this.wdrListeners.indexOf(listener);
      if (index >= 0) this.wdrListeners.splice(index, 1);
    };
  }

  /** Register a listener fired when SLEEP successfully enters a sleep mode. */
  onSleep(listener: (mode: number) => void): () => void {
    this.sleepListeners.push(listener);
    return () => {
      const index = this.sleepListeners.indexOf(listener);
      if (index >= 0) this.sleepListeners.splice(index, 1);
    };
  }

  /** Fired after wake entry, with the cycle at which wake began, before its cost. */
  onWake(listener: (wakeCycle: number) => void): () => void {
    this.wakeListeners.push(listener);
    return () => {
      const index = this.wakeListeners.indexOf(listener);
      if (index >= 0) this.wakeListeners.splice(index, 1);
    };
  }

  /** @internal Resume clock-domain synchronizers before wake-entry cycles. */
  onWakeStart(listener: (wakeCycle: number) => void): () => void {
    this.wakeStartListeners.push(listener);
    return () => {
      const index = this.wakeStartListeners.indexOf(listener);
      if (index >= 0) this.wakeStartListeners.splice(index, 1);
    };
  }

  /** @internal An asynchronous peripheral can wake before its CPU flag arrives. */
  wakeForPeripheral(): void {
    if (!this.sleeping) return;
    const wakeCycle = this.beginWake();
    this.cycles += 4;
    for (const listener of [...this.wakeListeners]) listener(wakeCycle);
  }

  private beginWake(): number {
    const wakeCycle = this.cycles;
    this.sleeping = false;
    for (const listener of [...this.wakeStartListeners]) listener(wakeCycle);
    return wakeCycle;
  }

  /** Called by the WDR instruction to reset the watchdog timer. */
  kickWatchdog(): void {
    for (const listener of [...this.wdrListeners]) listener();
  }

  // --- Stack pointer: little-endian across SPL (0x5D) / SPH (0x5E) ---
  get SP(): number {
    return this.data[SPL_ADDR]! | (this.data[SPH_ADDR]! << 8);
  }
  set SP(value: number) {
    this.data[SPL_ADDR] = value & 0xff;
    this.data[SPH_ADDR] = (value >> 8) & 0xff;
  }

  // --- Data-space access (the peripheral hook point) ---
  readData(addr: number): number {
    const hooks = this.readHooks[addr];
    if (hooks === undefined) return this.data[addr]!;
    const value = this.data[addr]!;
    // Almost every hooked address has exactly one hook; the direct call is a
    // monomorphic, allocation-free fast path (no for...of iterator).
    if (hooks.length === 1) {
      const result = hooks[0]!(this, addr);
      return result !== undefined ? result & 0xff : value;
    }
    let resolved = value;
    for (let i = 0; i < hooks.length; i += 1) {
      const result = hooks[i]!(this, addr);
      if (result !== undefined) resolved = result & 0xff;
    }
    return resolved;
  }
  writeData(addr: number, value: number): void {
    const masked = value & 0xff;
    const hooks = this.writeHooks[addr];
    if (hooks === undefined) {
      this.data[addr] = masked;
      return;
    }
    const oldValue = this.data[addr]!;
    this.data[addr] = masked;
    if (hooks.length === 1) {
      hooks[0]!(this, addr, masked, oldValue);
      return;
    }
    for (let i = 0; i < hooks.length; i += 1) hooks[i]!(this, addr, masked, oldValue);
  }

  /** Read one byte from program memory, with fuse/signature-row override support. */
  readProgramByte(byteAddr: number, readerPc = this.pc): number {
    const normalized = byteAddr & 0xffff;
    const override = this.programMemoryReadHook?.(normalized, readerPc);
    if (override !== undefined) return override & 0xff;
    const word = this.flash[normalized >> 1]!;
    return normalized & 1 ? (word >> 8) & 0xff : word & 0xff;
  }

  /** Install or clear the optional LPM special-row reader. */
  setProgramMemoryReadHook(hook: ProgramMemoryReadHook | undefined): void {
    this.programMemoryReadHook = hook;
  }

  /** Install or clear the optional SPM instruction handler. */
  setSpmInstructionHook(hook: SpmInstructionHook | undefined): void {
    this.spmInstructionHook = hook;
  }

  /** Called by the SPM instruction after decoding. */
  executeSpmInstruction(pc: number = this.pc): void {
    this.spmInstructionHook?.(pc);
  }

  /** Register a peripheral hook fired after `addr` is written (via writeData/OUT/ST...). */
  installWriteHook(addr: number, hook: IoWriteHook): void {
    (this.writeHooks[addr] ??= []).push(hook);
  }

  /** Remove a hook added with `installWriteHook` (no-op if absent). */
  removeWriteHook(addr: number, hook: IoWriteHook): void {
    const hooks = this.writeHooks[addr];
    const index = hooks?.indexOf(hook) ?? -1;
    if (index < 0) return;
    hooks!.splice(index, 1);
    // Unhooked addresses must read as `undefined` so the fast paths stay fast.
    if (hooks!.length === 0) this.writeHooks[addr] = undefined;
  }

  /** Register a peripheral hook consulted when `addr` is read (via readData/IN/LD...). */
  installReadHook(addr: number, hook: IoReadHook): void {
    (this.readHooks[addr] ??= []).push(hook);
  }

  /** Register a peripheral clock listener fired after every instruction. */
  onCycles(listener: CycleListener): () => void {
    this.cycleListeners.push(listener);
    return () => this.removeCycleListener(listener);
  }

  /**
   * Schedule `callback` to fire once, `cyclesFromNow` cycles from the current
   * cycle (minimum 1). The event fires when `cycles` next advances past it. The
   * `callback` identity is the handle for `clearClockEvent`; re-scheduling the
   * same callback is "clear then add". Replaces per-instruction `tick()` for
   * peripherals that know when their next event is due (Phase 7).
   */
  addClockEvent(callback: () => void, cyclesFromNow: number): void {
    this.clearClockEvent(callback);
    const at = this._cycles + normalizeClockEventDelay(cyclesFromNow);
    const entry = this.clockEventPool.pop() ?? { cycles: 0, callback, next: undefined };
    entry.cycles = at;
    entry.callback = callback;
    let prev: ClockEvent | undefined;
    let cur = this.nextClockEvent;
    while (cur !== undefined && cur.cycles <= at) {
      prev = cur;
      cur = cur.next;
    }
    entry.next = cur;
    if (prev === undefined) this.nextClockEvent = entry;
    else prev.next = entry;
    // Head is always defined here (we just inserted); refresh the scalar mirror.
    this.nextEventAt = this.nextClockEvent!.cycles;
  }

  /** Cancel the pending event scheduled with `callback` (no-op if none). */
  clearClockEvent(callback: () => void): void {
    let prev: ClockEvent | undefined;
    let cur = this.nextClockEvent;
    while (cur !== undefined) {
      if (cur.callback === callback) {
        if (prev === undefined) this.nextClockEvent = cur.next;
        else prev.next = cur.next;
        this.recycleClockEvent(cur);
        this.nextEventAt =
          this.nextClockEvent !== undefined ? this.nextClockEvent.cycles : Number.POSITIVE_INFINITY;
        return;
      }
      prev = cur;
      cur = cur.next;
    }
  }

  /** Remaining cycles for an event scheduled with `callback`, or 0 if absent. */
  clockEventRemainingCycles(callback: () => void): number {
    let cur = this.nextClockEvent;
    while (cur !== undefined) {
      if (cur.callback === callback) return normalizeClockEventDelay(cur.cycles - this._cycles);
      cur = cur.next;
    }
    return 0;
  }

  /** Fire every event whose cycle boundary has been reached. */
  private runDueClockEvents(): void {
    let event = this.nextClockEvent;
    while (event !== undefined && event.cycles <= this._cycles) {
      this.nextClockEvent = event.next;
      const callback = event.callback;
      this.recycleClockEvent(event);
      callback(); // may schedule new events (e.g. a peripheral re-arming)
      event = this.nextClockEvent;
    }
    this.nextEventAt =
      this.nextClockEvent !== undefined ? this.nextClockEvent.cycles : Number.POSITIVE_INFINITY;
  }

  private recycleClockEvent(event: ClockEvent): void {
    event.callback = NOOP;
    event.next = undefined;
    if (this.clockEventPool.length < 16) this.clockEventPool.push(event);
  }

  /** @internal Observe hardware flag edges used as ADC auto-trigger inputs. */
  onInterruptFlag(address: number, listener: (raised: number) => void): () => void {
    const listeners = this.flagListeners[address] ??= [];
    listeners.push(listener);
    return () => {
      const index = listeners.indexOf(listener);
      if (index >= 0) listeners.splice(index, 1);
    };
  }

  /** @internal Assert hardware flags and deliver edges before ISR acknowledgement. */
  setInterruptFlag(address: number, mask: number): void {
    const oldValue = this.data[address]!;
    this.data[address] = oldValue | mask;
    const raised = mask & ~oldValue;
    if (raised !== 0) {
      for (const listener of this.flagListeners[address] ?? []) listener(raised);
    }
  }

  /** Queue an interrupt by vector address; lowest vector has highest priority. */
  requestInterrupt(vector: number, acknowledge?: () => void): void {
    if (this.pendingInterrupts.some((pending) => pending.vector === vector)) return;
    this.pendingInterrupts.push({ vector, acknowledge });
    this.pendingInterrupts.sort((a, b) => a.vector - b.vector);
  }

  /** Withdraw a peripheral request whose flag or enable bit has been cleared. */
  clearInterrupt(vector: number): void {
    const index = this.pendingInterrupts.findIndex((pending) => pending.vector === vector);
    if (index >= 0) this.pendingInterrupts.splice(index, 1);
  }

  /** @internal SEI/RETI must finish without dispatching an interrupt. */
  deferInterrupts(): void {
    this.interruptDeferred = true;
  }

  // --- I/O-space access: IN/OUT address A maps to data[A + 0x20] ---
  readIo(ioAddr: number): number {
    return this.readData(ioAddr + IO_BASE);
  }
  writeIo(ioAddr: number, value: number): void {
    this.writeData(ioAddr + IO_BASE, value);
  }

  // --- Stack (grows downward; SP points at the next free byte) ---
  pushByte(value: number): void {
    const sp = this.SP;
    // Stack writes are data writes too: watchpoints (and, on stack overflow
    // into IO space, peripheral hooks) must observe them.
    if (this.writeHooks[sp] === undefined) this.data[sp] = value & 0xff;
    else this.writeData(sp, value);
    this.SP = (sp - 1) & 0xffff;
  }

  popByte(): number {
    this.SP = (this.SP + 1) & 0xffff;
    return this.data[this.SP]!;
  }

  /** Push a 16-bit word (e.g. a return address): high byte lands at the lower address. */
  pushWord(value: number): void {
    this.pushByte(value & 0xff);
    this.pushByte((value >> 8) & 0xff);
  }

  popWord(): number {
    const high = this.popByte();
    const low = this.popByte();
    return (high << 8) | low;
  }

  // --- Execution ---
  /** Attach the decoder/executor that runs opcodes (keeps modules acyclic). */
  setExecutor(executor: Executor): void {
    this.executor = executor;
    this.invalidateDecodeCache();
  }

  /**
   * Drop the predecode cache. Call this after mutating `flash` directly (the
   * low-level escape hatch) so stale handlers/blocks cannot execute old code.
   * `reset()`, `restore()`, and `setExecutor()` invalidate automatically.
   */
  invalidateDecodeCache(): void {
    this.decodeCache.length = 0;
    this.fastBlockCache.length = 0;
  }

  /** Fetch, decode, and execute one instruction (or idle one cycle while asleep). */
  tick(): void {
    // Guard on size first: the common case has no breakpoints, so this skips
    // the Set hash lookup on every instruction.
    if (this.breakpoints.size > 0 && this.breakpoints.has(this.pc)) {
      this._breakpointHit = true;
      return;
    }
    if (this.sleeping) {
      // The `cycles` setter fires cycle listeners (one per simulated cycle in
      // cycle-exact mode, otherwise coalesced).
      this.cycles += 1;
      this.serviceInterrupts();
      return;
    }
    const executor = this.executor;
    if (!executor) {
      throw new Error("CPU has no executor — call setExecutor(new Decoder()) first.");
    }
    const pc = this.pc;
    const opcode = this.flash[pc]!;
    try {
      // Each `cpu.cycles += N` inside the handler goes through the setter and
      // fires cycle listeners with the configured granularity. No explicit
      // notifyCycles call is needed here.
      //
      // Phase 4 predecode: reuse the handler resolved for this PC. On a miss,
      // resolve once and cache it; an unknown opcode falls through to
      // `executor.execute()` so the rich UnknownOpcodeError is still thrown.
      let handler = this.decodeCache[pc];
      if (handler === undefined) {
        // Out-of-flash PCs are never cached, so the wrap check costs nothing on
        // the hot path. Re-enter so the wrapped PC gets the breakpoint check.
        if (this.wrapProgramCounter()) {
          this.tick();
          return;
        }
        handler = executor.handlerFor(opcode);
        if (handler === undefined) {
          executor.execute(this, opcode); // throws UnknownOpcodeError
          return;
        }
        this.decodeCache[pc] = handler;
      }
      handler(this, opcode);
    } catch (e) {
      if (e instanceof UnknownOpcodeError && this.pauseOnUnknownOpcode) {
        this._error = e;
        return;
      }
      throw e;
    }
    this.serviceInterrupts();
    if (this.traceListeners.length > 0) {
      this.emitTrace({
        pc,
        opcode,
        mnemonic: executor.mnemonicOf(opcode) ?? "???",
        cycles: this.cycles,
      });
    }
  }

  /**
   * @internal generated-core surface (see generated/cores.ts).
   * Wrap a PC that ran off either end of flash, as the chip's 14-bit PC does
   * (e.g. sliding through an empty boot section back to the application at 0).
   * Returns true when the PC was out of range and has been wrapped.
   */
  wrapProgramCounter(): boolean {
    const pc = this.pc;
    const words = this.flash.length;
    if (pc >= 0 && pc < words) return false;
    this.pc = ((pc % words) + words) % words;
    return true;
  }

  /** Run until at least `maxCycles` additional cycles have elapsed or a debug stop fires. */
  run(maxCycles: number): void {
    this._breakpointHit = false;
    const target = this._cycles + maxCycles;
    if (this.canUseFastRun()) runGeneratedFastCore(this, target);
    else this.runTicksUntil(target);
    // Observers (debugger, snapshots) only ever see an in-flash PC.
    this.wrapProgramCounter();
  }

  /**
   * Run with the same fast path as `run()`, but emit coarse profiling events.
   * Intended for benchmark scripts; debugger tracing still uses `onTrace()`.
   */
  profileRun(maxCycles: number, listener: ProfileRunListener): void {
    this._breakpointHit = false;
    const target = this._cycles + maxCycles;
    if (this.canUseFastRun()) {
      runFastProfiled(this, target, listener);
      return;
    }

    this.runProfiledTicks(target, listener);
  }

  /** @internal generated-core surface (see generated/cores.ts). */
  runProfiledTicks(target: number, listener: ProfileRunListener): void {
    const executor = this.executor;
    if (!executor) {
      throw new Error("CPU has no executor — call setExecutor(new Decoder()) first.");
    }
    while (this._cycles < target) {
      const pc = this.pc;
      const opcode = this.flash[pc]!;
      const before = this._cycles;
      const sleeping = this.sleeping;
      this.tick();
      if (this._cycles !== before) {
        listener(this.profileState(pc, opcode, before, sleeping ? "sleep" : "instruction"));
      }
      if (this._breakpointHit) return;
      if (this._error !== null) return;
    }
  }

  private canUseFastRun(): boolean {
    return (
      this.breakpoints.size === 0 &&
      this.traceListeners.length === 0 &&
      !this.pauseOnUnknownOpcode
    );
  }

  /** @internal generated-core surface (see generated/cores.ts). */
  runTicksUntil(target: number): void {
    while (this._cycles < target) {
      this.tick();
      if (this._breakpointHit) return;
      if (this._error !== null) return;
    }
  }

  /** @internal generated-core surface (see generated/cores.ts). */
  profileFastBlock(
    listener: ProfileRunListener,
    pc: number,
    opcode: number,
    before: number,
  ): void {
    listener(
      this.profileState(
        pc,
        opcode,
        before,
        "fast-block",
        fastBlockProfileKind(this.fastBlockCache[pc] ?? FAST_BLOCK_NONE),
      ),
    );
  }

  /** @internal generated-core surface (see generated/cores.ts). */
  profileState(
    pc: number,
    opcode: number,
    beforeCycles: number,
    kind: ProfileRunState["kind"],
    blockKind?: ProfileRunState["blockKind"],
  ): ProfileRunState {
    const state: ProfileRunState = {
      pc,
      opcode,
      mnemonic: this.executor?.mnemonicOf(opcode) ?? "???",
      cycles: this.cycles,
      elapsedCycles: this._cycles - beforeCycles,
      kind,
    };
    if (blockKind !== undefined) state.blockKind = blockKind;
    return state;
  }

  /** @internal generated-core surface (see generated/cores.ts). */
  tryRunFastBlock(pc: number, opcode: number, target: number): boolean {
    let kind = this.fastBlockCache[pc] ?? FAST_BLOCK_UNKNOWN;
    if (kind === FAST_BLOCK_UNKNOWN) {
      kind = classifyFastBlock(this, pc, opcode);
      this.fastBlockCache[pc] = kind;
    }
    return runFastBlock(this, kind, pc, opcode, target);
  }

  /** @internal fast-block surface (see fast-blocks.ts). */
  bulkIdleLoopIterations(target: number, cyclesPerIteration: number): number {
    if (
      this.timing !== "fast" ||
      this.cycleListeners.length !== 0 ||
      (this.pendingInterrupts.length !== 0 && (this.data[SREG_ADDR]! & SREG_I) !== 0)
    ) {
      return 0;
    }

    let limit = target;
    const nextEvent = this.nextClockEvent;
    if (nextEvent !== undefined && nextEvent.cycles <= limit) limit = nextEvent.cycles - 1;
    return Math.floor((limit - this._cycles) / cyclesPerIteration);
  }

  /** @internal generated-core surface (see generated/cores.ts). */
  canRunFastBlock(target: number, blockCycles: number): boolean {
    if (
      this.timing !== "fast" ||
      this.cycleListeners.length !== 0 ||
      (this.pendingInterrupts.length !== 0 && (this.data[SREG_ADDR]! & SREG_I) !== 0)
    ) {
      return false;
    }
    const finalCycles = this._cycles + blockCycles;
    if (finalCycles > target) return false;
    const nextEvent = this.nextClockEvent;
    return nextEvent === undefined || nextEvent.cycles > finalCycles;
  }

  // --- Debug/trace hook (used heavily from Phase 2 on) ---
  onTrace(listener: TraceListener): () => void {
    this.traceListeners.push(listener);
    return () => this.removeTrace(listener);
  }

  /** Emit a trace record to all listeners (called by the execute loop later). */
  emitTrace(state: TraceState): void {
    for (const listener of this.traceListeners) listener(state);
  }

  private removeTrace(listener: TraceListener): void {
    const index = this.traceListeners.indexOf(listener);
    if (index >= 0) this.traceListeners.splice(index, 1);
  }

  private removeCycleListener(listener: CycleListener): void {
    if (this.cycleListenerDispatchDepth > 0) {
      const depth = this.cycleListenerDispatchDepth;
      const existingDepth = this.pendingCycleListenerRemovalDepths.get(listener);
      if (existingDepth === undefined) {
        this.pendingCycleListenerRemovals.push(listener);
        this.pendingCycleListenerRemovalDepths.set(listener, depth);
      } else if (depth < existingDepth) {
        this.pendingCycleListenerRemovalDepths.set(listener, depth);
      }
      return;
    }
    this.spliceCycleListener(listener);
  }

  private spliceCycleListener(listener: CycleListener): void {
    const index = this.cycleListeners.indexOf(listener);
    if (index >= 0) this.cycleListeners.splice(index, 1);
  }

  /** Fire cycle listeners for `elapsed` consumed cycles (peripherals advance time). */
  private notifyCycles(elapsed: number): void {
    if (elapsed <= 0) return;
    const listeners = this.cycleListeners;
    const count = listeners.length;
    if (count === 0) return;

    // Hot path: a top-level notification with no removals pending — the case on
    // essentially every instruction, since cycle listeners are wired once and
    // almost never unsubscribe mid-run. This skips the deferred-removal
    // bookkeeping (a per-call Map.clear() + array drain + the removalDepths
    // lookups) that otherwise dominated the per-instruction cost. A listener that
    // unsubscribes *during* this loop is still called this round; its removal is
    // drained afterward — matching the slow path's "removed at this depth still
    // fires this round" semantics.
    if (
      this.cycleListenerDispatchDepth === 0 &&
      this.pendingCycleListenerRemovalDepths.size === 0
    ) {
      this.cycleListenerDispatchDepth = 1;
      try {
        for (let i = 0; i < count; i += 1) listeners[i]!(elapsed, this);
      } finally {
        this.cycleListenerDispatchDepth = 0;
        if (this.pendingCycleListenerRemovals.length > 0) this.drainCycleListenerRemovals();
      }
      return;
    }

    // Slow path: reentrant (nested notification) or removals already pending. Use
    // the full depth-aware bookkeeping so an unsubscribe during a nested
    // notification applies to deeper dispatches without perturbing the active one.
    this.cycleListenerDispatchDepth += 1;
    const dispatchDepth = this.cycleListenerDispatchDepth;
    const removalDepths =
      this.pendingCycleListenerRemovalDepths.size > 0
        ? this.pendingCycleListenerRemovalDepths
        : undefined;
    try {
      if (removalDepths === undefined) {
        for (let i = 0; i < count; i += 1) listeners[i]!(elapsed, this);
      } else {
        for (let i = 0; i < count; i += 1) {
          const listener = listeners[i]!;
          const removalDepth = removalDepths.get(listener);
          if (removalDepth !== undefined && removalDepth < dispatchDepth) continue;
          listener(elapsed, this);
        }
      }
    } finally {
      this.cycleListenerDispatchDepth -= 1;
      if (this.cycleListenerDispatchDepth === 0 && this.pendingCycleListenerRemovals.length > 0) {
        this.drainCycleListenerRemovals();
      }
    }
  }

  private drainCycleListenerRemovals(): void {
    for (const listener of this.pendingCycleListenerRemovals) this.spliceCycleListener(listener);
    this.pendingCycleListenerRemovals.length = 0;
    this.pendingCycleListenerRemovalDepths.clear();
  }

  /**
   * Service one pending interrupt, then bill its entry cost (the 4 dispatch
   * cycles) to the peripherals so timers/watchdog/ADC keep accurate time while an
   * interrupt is taken. Peripherals have already ticked for this instruction, so
   * any interrupt they just queued is honored here before the cost is billed.
   */
  /** @internal generated-core surface (see generated/cores.ts). */
  serviceInterrupts(): void {
    if (this.interruptDeferred) {
      this.interruptDeferred = false;
      return;
    }
    // The `cycles += 4` in serviceNextInterrupt goes through the setter, which
    // already fires cycle listeners at the configured granularity. No extra
    // notifyCycles call is needed here.
    this.serviceNextInterrupt();
  }

  private serviceNextInterrupt(): void {
    // Check the cheap array length before the SREG accessor: most ticks have no
    // pending interrupt, so this avoids the flag bit-math on the common path.
    if (this.pendingInterrupts.length === 0) return;
    if (!this.sreg.I) {
      if (this.sleeping) {
        this.wakeForPeripheral();
      }
      return;
    }
    const interrupt = this.pendingInterrupts.shift()!;
    const wasSleeping = this.sleeping;
    const wakeCycle = wasSleeping ? this.beginWake() : this.cycles;
    interrupt.acknowledge?.();
    this.pushWord(this.pc);
    this.sreg.I = false;
    this.pc = this.interruptVectorBase + interrupt.vector;
    this.cycles += wasSleeping ? 8 : 4;
    if (wasSleeping) {
      for (const listener of [...this.wakeListeners]) listener(wakeCycle);
    }
  }

  // --- Debug accessors (Phase 11) ---

  /** True when the most recent `tick()` / `run()` was stopped by a breakpoint. */
  get wasBreakpointHit(): boolean {
    return this._breakpointHit;
  }

  /** Clear the breakpoint-hit flag at the start of a new run. */
  clearBreakpointHit(): void {
    this._breakpointHit = false;
  }

  /**
   * Captured error from the most recent `tick()` / `run()` (e.g. an unknown
   * opcode when `pauseOnUnknownOpcode` is enabled). Null when no error.
   */
  get error(): unknown {
    return this._error;
  }

  /** Clear the captured error so a subsequent run starts fresh. */
  clearError(): void {
    this._error = null;
  }

  // --- Snapshot / restore (Phase 10) ---

  /**
   * Capture CPU state as plain data. Flash and the data-space are copied so the
   * snapshot is independent of further CPU activity. Pending interrupt acknowledge
   * callbacks (which capture `this` of peripherals) are intentionally dropped —
   * ISRs will clear their own flags via TIFR writes on entry.
   */
  snapshot(): CpuSnapshot {
    return {
      pc: this.pc,
      cycles: this.cycles,
      sleeping: this.sleeping,
      data: new Uint8Array(this.data),
      flash: new Uint16Array(this.flash),
      pendingInterrupts: this.pendingInterrupts.map((p) => p.vector),
      interruptVectorBase: this.interruptVectorBase,
      interruptDeferred: this.interruptDeferred,
    };
  }

  /**
   * Replace CPU state from a snapshot. Does not fire peripheral write hooks (it
   * writes `data` directly) — peripherals that need a resync should call their own
   * `resync()` or be restored explicitly by the runtime.
   */
  restore(snap: CpuSnapshot, acknowledgeForVector?: InterruptAcknowledgeResolver): void {
    this.pc = snap.pc;
    this.interruptVectorBase = snap.interruptVectorBase ?? 0;
    this._cycles = snap.cycles;
    this.sleeping = snap.sleeping;
    this.interruptDeferred = snap.interruptDeferred ?? false;
    this.data.set(snap.data);
    this.flash.set(snap.flash);
    this.invalidateDecodeCache(); // restored flash may differ from the cached program
    this.nextClockEvent = undefined; // peripherals re-arm their events in restore()
    this.nextEventAt = Number.POSITIVE_INFINITY;
    this.pendingInterrupts.length = 0;
    for (const vector of snap.pendingInterrupts) {
      this.pendingInterrupts.push({ vector, acknowledge: acknowledgeForVector?.(vector) });
    }
    this.pendingInterrupts.sort((a, b) => a.vector - b.vector);
  }
}
