const GENERATED_FAST_CORE_URL = new URL("../src/cpu/generated/fast-core.ts", import.meta.url);
const CPU_SOURCE_URL = new URL("../src/cpu/cpu.ts", import.meta.url);

const GENERATED_REGION_BEGIN = "  // BEGIN GENERATED FAST CORE";
const GENERATED_REGION_END = "  // END GENERATED FAST CORE";

export const GENERATED_FAST_CORE_PATH = GENERATED_FAST_CORE_URL;
export const CPU_FAST_CORE_PATH = CPU_SOURCE_URL;

interface GeneratedArm {
  name: string;
  guard: string;
  body: readonly string[];
}

const GENERATED_ARMS: readonly GeneratedArm[] = [
  {
    name: "zero-sbiw-breq-block",
    guard: "(opcode & 0xffcf) === 0x9700 && this.tryRunFastBlock(pc, opcode, target)",
    body: ["continue;"],
  },
  {
    name: "nop",
    guard: "opcode === 0x0000",
    body: ["this.pc += 1;", "this.cycles += 1;"],
  },
  {
    name: "rjmp",
    guard: "(opcode & 0xf000) === 0xc000",
    body: [
      "const k = opcode & 0x0fff;",
      "if (k === 0x0fff && this.tryRunFastBlock(pc, opcode, target)) continue;",
      "this.pc += (k >= 0x800 ? k - 0x1000 : k) + 1;",
      "this.cycles += 2;",
    ],
  },
  {
    name: "branch-if-set",
    guard: "(opcode & 0xfc00) === 0xf000",
    body: [
      "if ((data[SREG_ADDR]! & (1 << (opcode & 0x07))) !== 0) {",
      "  const k = (opcode >> 3) & 0x7f;",
      "  this.pc += (k >= 0x40 ? k - 0x80 : k) + 1;",
      "  this.cycles += 2;",
      "} else {",
      "  this.pc += 1;",
      "  this.cycles += 1;",
      "}",
    ],
  },
  {
    name: "branch-if-clear",
    guard: "(opcode & 0xfc00) === 0xf400",
    body: [
      "if ((data[SREG_ADDR]! & (1 << (opcode & 0x07))) === 0) {",
      "  const k = (opcode >> 3) & 0x7f;",
      "  this.pc += (k >= 0x40 ? k - 0x80 : k) + 1;",
      "  this.cycles += 2;",
      "} else {",
      "  this.pc += 1;",
      "  this.cycles += 1;",
      "}",
    ],
  },
  {
    name: "sbiw",
    guard: "(opcode & 0xff00) === 0x9700",
    body: [
      "const d = 24 + (((opcode >> 4) & 0x03) * 2);",
      "const k = (opcode & 0x0f) | ((opcode >> 2) & 0x30);",
      "const before = data[d]! | (data[d + 1]! << 8);",
      "const result = (before - k) & 0xffff;",
      "data[d] = result & 0xff;",
      "data[d + 1] = (result >> 8) & 0xff;",
      "const n = (result & 0x8000) !== 0;",
      "const v = (before & ~result & 0x8000) !== 0;",
      "const flags =",
      "  (v ? SREG_V : 0) |",
      "  (n ? SREG_N : 0) |",
      "  (result === 0 ? SREG_Z : 0) |",
      "  (before < k ? SREG_C : 0) |",
      "  (n !== v ? SREG_S : 0);",
      "data[SREG_ADDR] = (data[SREG_ADDR]! & ~SREG_WORD_MASK) | flags;",
      "this.pc += 1;",
      "this.cycles += 2;",
    ],
  },
  {
    name: "ldi",
    guard: "(opcode & 0xf000) === 0xe000",
    body: ["data[regD4(opcode)] = imm8(opcode);", "this.pc += 1;", "this.cycles += 1;"],
  },
  {
    name: "mov",
    guard: "(opcode & 0xfc00) === 0x2c00",
    body: ["data[regD5(opcode)] = data[regR5(opcode)]!;", "this.pc += 1;", "this.cycles += 1;"],
  },
  {
    name: "shift-left-dec-block",
    guard: "(opcode & 0xfc00) === 0x0c00 && this.tryRunFastBlock(pc, opcode, target)",
    body: ["continue;"],
  },
  {
    name: "arduino-micros-block",
    guard: "opcode === 0xb73f && this.tryRunFastBlock(pc, opcode, target)",
    body: ["continue;"],
  },
  {
    name: "call",
    guard: "(opcode & 0xfe0e) === 0x940e",
    body: [
      "this.pushWord(pc + 2);",
      "const high = ((opcode & 0x01f0) >> 3) | (opcode & 0x0001);",
      "this.pc = (high << 16) | flash[pc + 1]!;",
      "this.cycles += 4;",
    ],
  },
];

export function generatedFastCoreArmNames(): readonly string[] {
  return GENERATED_ARMS.map((arm) => arm.name);
}

export function generateFastCoreSource(): string {
  return [
    "// This file is generated by scripts/generate-fast-core.ts.",
    "// Do not edit by hand; run `bun run generate:fast-core` instead.",
    "",
    "export const GENERATED_FAST_CORE_METHOD_NAME = \"runGeneratedFastCore\";",
    "export const GENERATED_FAST_CORE_ARM_NAMES = [",
    ...GENERATED_ARMS.map((arm) => `  ${JSON.stringify(arm.name)},`),
    "] as const;",
    "",
  ].join("\n");
}

export function generateFastCoreRegion(): string {
  return [
    GENERATED_REGION_BEGIN,
    ...generateFastCoreMethodLines(),
    GENERATED_REGION_END,
  ].join("\n");
}

function generateFastCoreMethodLines(): string[] {
  return [
    "  private runGeneratedFastCore(target: number): void {",
    "    const executor = this.executor;",
    "    if (!executor) {",
    '      throw new Error("CPU has no executor - call setExecutor(new Decoder()) first.");',
    "    }",
    "    const flash = this.flash;",
    "    const data = this.data;",
    "    const decodeCache = this.decodeCache;",
    "    while (this._cycles < target) {",
    "      if (this.sleeping) {",
    "        this.tick();",
    "      } else {",
    "        const pc = this.pc;",
    "        const opcode = flash[pc]!;",
    ...indentLines(generateLadderLines(), 8),
    "        this.serviceInterrupts();",
    "      }",
    "      if (",
    "        this.breakpoints.size !== 0 ||",
    "        this.traceListeners.length !== 0 ||",
    "        this.pauseOnUnknownOpcode",
    "      ) {",
    "        this.runTicksUntil(target);",
    "        return;",
    "      }",
    "    }",
    "  }",
  ];
}

function generateLadderLines(): string[] {
  const lines: string[] = [];
  GENERATED_ARMS.forEach((arm, index) => {
    lines.push(`${index === 0 ? "if" : "else if"} (${arm.guard}) {`);
    lines.push(...indentLines([...arm.body], 2));
    lines.push("}");
  });
  lines.push("else {");
  lines.push(...indentLines(generateFallbackLines(), 2));
  lines.push("}");
  return lines;
}

function generateFallbackLines(): string[] {
  return [
    "let handler = decodeCache[pc];",
    "if (handler === undefined) {",
    "  handler = executor.handlerFor(opcode);",
    "  if (handler === undefined) {",
    "    executor.execute(this, opcode);",
    "    this.serviceInterrupts();",
    "    continue;",
    "  }",
    "  decodeCache[pc] = handler;",
    "}",
    "handler(this, opcode);",
  ];
}

function indentLines(lines: readonly string[], spaces: number): string[] {
  const prefix = " ".repeat(spaces);
  return lines.map((line) => (line.length === 0 ? line : `${prefix}${line}`));
}

function replaceGeneratedRegion(source: string, region: string): string {
  const begin = source.indexOf(GENERATED_REGION_BEGIN);
  if (begin < 0) {
    throw new Error(`Missing generated fast core marker: ${GENERATED_REGION_BEGIN}`);
  }
  const end = source.indexOf(GENERATED_REGION_END, begin);
  if (end < 0) {
    throw new Error(`Missing generated fast core marker: ${GENERATED_REGION_END}`);
  }
  const afterEnd = end + GENERATED_REGION_END.length;
  return `${source.slice(0, begin)}${region}${source.slice(afterEnd)}`;
}

function extractGeneratedRegion(source: string): string {
  const begin = source.indexOf(GENERATED_REGION_BEGIN);
  if (begin < 0) {
    throw new Error(`Missing generated fast core marker: ${GENERATED_REGION_BEGIN}`);
  }
  const end = source.indexOf(GENERATED_REGION_END, begin);
  if (end < 0) {
    throw new Error(`Missing generated fast core marker: ${GENERATED_REGION_END}`);
  }
  return source.slice(begin, end + GENERATED_REGION_END.length);
}

async function main(): Promise<void> {
  const check = Bun.argv.includes("--check");
  const metadataSource = generateFastCoreSource();
  const region = generateFastCoreRegion();
  if (check) {
    const existingMetadata = await Bun.file(GENERATED_FAST_CORE_URL).text().catch(() => "");
    if (existingMetadata !== metadataSource) {
      console.error("Generated fast core metadata is stale. Run `bun run generate:fast-core`.");
      process.exit(1);
    }
    const cpuSource = await Bun.file(CPU_SOURCE_URL).text();
    if (extractGeneratedRegion(cpuSource) !== region) {
      console.error("Class-local generated fast core is stale. Run `bun run generate:fast-core`.");
      process.exit(1);
    }
    return;
  }

  await Bun.write(GENERATED_FAST_CORE_URL, metadataSource);
  const cpuSource = await Bun.file(CPU_SOURCE_URL).text();
  await Bun.write(CPU_SOURCE_URL, replaceGeneratedRegion(cpuSource, region));
}

if (import.meta.main) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  });
}
