const GENERATED_FAST_CORE_URL = new URL("../src/cpu/generated/fast-core.ts", import.meta.url);

export const GENERATED_FAST_CORE_PATH = GENERATED_FAST_CORE_URL;

interface GeneratedArm {
  name: string;
  guard: string;
  body: readonly string[];
}

const GENERATED_ARMS: readonly GeneratedArm[] = [
  {
    name: "zero-sbiw-breq-block",
    guard: "(opcode & 0xffcf) === 0x9700 && self.tryRunFastBlock(pc, opcode, target)",
    body: ["continue;"],
  },
  {
    name: "nop",
    guard: "opcode === 0x0000",
    body: ["self.pc += 1;", "self.cycles += 1;"],
  },
  {
    name: "rjmp",
    guard: "(opcode & 0xf000) === 0xc000",
    body: [
      "const k = opcode & 0x0fff;",
      "if (k === 0x0fff && self.tryRunFastBlock(pc, opcode, target)) continue;",
      "self.pc += (k >= 0x800 ? k - 0x1000 : k) + 1;",
      "self.cycles += 2;",
    ],
  },
  {
    name: "branch-if-set",
    guard: "(opcode & 0xfc00) === 0xf000",
    body: [
      "if ((data[SREG_ADDR]! & (1 << (opcode & 0x07))) !== 0) {",
      "  const k = (opcode >> 3) & 0x7f;",
      "  self.pc += (k >= 0x40 ? k - 0x80 : k) + 1;",
      "  self.cycles += 2;",
      "} else {",
      "  self.pc += 1;",
      "  self.cycles += 1;",
      "}",
    ],
  },
  {
    name: "branch-if-clear",
    guard: "(opcode & 0xfc00) === 0xf400",
    body: [
      "if ((data[SREG_ADDR]! & (1 << (opcode & 0x07))) === 0) {",
      "  const k = (opcode >> 3) & 0x7f;",
      "  self.pc += (k >= 0x40 ? k - 0x80 : k) + 1;",
      "  self.cycles += 2;",
      "} else {",
      "  self.pc += 1;",
      "  self.cycles += 1;",
      "}",
    ],
  },
  {
    name: "sbiw",
    guard: "(opcode & 0xff00) === 0x9700",
    body: [
      "const d = 24 + (((opcode >> 4) & 0x03) * 2);",
      "const k = (opcode & 0x0f) | ((opcode >> 2) & 0x30);",
      "const before = data[d]! | (data[d + 1]! << 8);",
      "const result = (before - k) & 0xffff;",
      "data[d] = result & 0xff;",
      "data[d + 1] = (result >> 8) & 0xff;",
      "const n = (result & 0x8000) !== 0;",
      "const v = (before & ~result & 0x8000) !== 0;",
      "const flags =",
      "  (v ? SREG_V : 0) |",
      "  (n ? SREG_N : 0) |",
      "  (result === 0 ? SREG_Z : 0) |",
      "  (before < k ? SREG_C : 0) |",
      "  (n !== v ? SREG_S : 0);",
      "data[SREG_ADDR] = (data[SREG_ADDR]! & ~SREG_WORD_MASK) | flags;",
      "self.pc += 1;",
      "self.cycles += 2;",
    ],
  },
  {
    name: "ldi",
    guard: "(opcode & 0xf000) === 0xe000",
    body: ["data[regD4(opcode)] = imm8(opcode);", "self.pc += 1;", "self.cycles += 1;"],
  },
  {
    name: "mov",
    guard: "(opcode & 0xfc00) === 0x2c00",
    body: ["data[regD5(opcode)] = data[regR5(opcode)]!;", "self.pc += 1;", "self.cycles += 1;"],
  },
  {
    name: "shift-left-dec-block",
    guard: "(opcode & 0xfc00) === 0x0c00 && self.tryRunFastBlock(pc, opcode, target)",
    body: ["continue;"],
  },
  {
    name: "arduino-micros-block",
    guard: "opcode === 0xb73f && self.tryRunFastBlock(pc, opcode, target)",
    body: ["continue;"],
  },
];

export function generatedFastCoreArmNames(): readonly string[] {
  return GENERATED_ARMS.map((arm) => arm.name);
}

export function generateFastCoreSource(): string {
  const lines: string[] = [
    "// This file is generated by scripts/generate-fast-core.ts.",
    "// Do not edit by hand; run `bun run generate:fast-core` instead.",
    'import type { CPU } from "../cpu";',
    'import { SREG_ADDR } from "../constants";',
    "import {",
    "  SREG_C,",
    "  SREG_N,",
    "  SREG_S,",
    "  SREG_V,",
    "  SREG_WORD_MASK,",
    "  SREG_Z,",
    "  imm8,",
    "  regD4,",
    "  regD5,",
    "  regR5,",
    '} from "../alu";',
    "",
    "export const GENERATED_FAST_CORE_ARM_NAMES = [",
    ...GENERATED_ARMS.map((arm) => `  ${JSON.stringify(arm.name)},`),
    "] as const;",
    "",
    "export function runGeneratedFastCore(this: CPU, target: number): void {",
    "  const self = this as any;",
    "  const executor = self.executor;",
    "  if (!executor) {",
    '    throw new Error("CPU has no executor - call setExecutor(new Decoder()) first.");',
    "  }",
    "  const flash = self.flash as Uint16Array;",
    "  const data = self.data as Uint8Array;",
    "  const decodeCache = self.decodeCache as Array<((cpu: CPU, opcode: number) => void) | undefined>;",
    "  while (self._cycles < target) {",
    "    if (self.sleeping) {",
    "      self.tick();",
    "    } else {",
    "      const pc = self.pc as number;",
    "      const opcode = flash[pc]!;",
    ...indentLines(generateLadderLines(), 6),
    "      self.serviceInterrupts();",
    "    }",
    "    if (",
    "      self.breakpoints.size !== 0 ||",
    "      self.traceListeners.length !== 0 ||",
    "      self.pauseOnUnknownOpcode",
    "    ) {",
    "      self.runTicksUntil(target);",
    "      return;",
    "    }",
    "  }",
    "}",
    "",
  ];
  return `${lines.join("\n")}`;
}

function generateLadderLines(): string[] {
  const lines: string[] = [];
  GENERATED_ARMS.forEach((arm, index) => {
    lines.push(`${index === 0 ? "if" : "else if"} (${arm.guard}) {`);
    lines.push(...indentLines([...arm.body], 2));
    lines.push("}");
  });
  lines.push("else {");
  lines.push(...indentLines(generateFallbackLines(), 2));
  lines.push("}");
  return lines;
}

function generateFallbackLines(): string[] {
  return [
    "let handler = decodeCache[pc];",
    "if (handler === undefined) {",
    "  handler = executor.handlerFor(opcode);",
    "  if (handler === undefined) {",
    "    executor.execute(self, opcode);",
    "    self.serviceInterrupts();",
    "    continue;",
    "  }",
    "  decodeCache[pc] = handler;",
    "}",
    "handler(self, opcode);",
  ];
}

function indentLines(lines: readonly string[], spaces: number): string[] {
  const prefix = " ".repeat(spaces);
  return lines.map((line) => (line.length === 0 ? line : `${prefix}${line}`));
}

async function main(): Promise<void> {
  const check = Bun.argv.includes("--check");
  const source = generateFastCoreSource();
  if (check) {
    const existing = await Bun.file(GENERATED_FAST_CORE_URL).text().catch(() => "");
    if (existing !== source) {
      console.error("Generated fast core is stale. Run `bun run generate:fast-core`.");
      process.exit(1);
    }
    return;
  }
  await Bun.write(GENERATED_FAST_CORE_URL, source);
}

if (import.meta.main) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  });
}
